### ISSUE TITLE
pSc monitor::    add `--filter-test` option 

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#602] opened 2018-03-20 15:36 UTC
similar to `pscheduler schedule --filter-test=`
On hosts with a long list of running `latencybg` tasks it is impossible to see what is happening with other tasks.

**Comment by mfeit-internet2** [comment] 2018-03-20 15:37
Duplicate of #355.

**Closed by mfeit-internet2** 2018-03-20 15:37 UTC
Labels: enhancement
