### ISSUE TITLE
iperf3 requires exactly 2 participants, got 1

### ISSUE THREAD

**Issue by vvidic** [perfsonar/pscheduler#476] opened 2017-06-12 11:22 UTC
```
Jun 12 13:12:11 pstest2 runner INFO     134287: Running https://pstest2.geant.carnet.hr/pscheduler/tasks/a150319e-cd2e-4166-84ea-4ebae0ba01db/runs/b572656f-e025-4bb1-a3dc-a83a64b6afcc
Jun 12 13:12:11 pstest2 runner INFO     134287: With iperf3: throughput --bandwidth 50000000 --duration PT10S --source psps-test2-mgmt.rrze.uni-erlangen.de --ip-version 4 --dest pstest2.geant.carnet.hr --window-size 1024000 --parallel 1 --udp
Jun 12 13:12:11 pstest2 runner INFO     134287: Run failed 1: iperf3 requires exactly 2 participants, got 1
Jun 12 13:12:12 pstest2 pscheduler-api ERROR    Exception: InternalError: Unable to get merged result on {"test": {"spec": {"udp": true, "dest": "pstest2.geant.carnet.hr", "schema": 1, "source": "psps-test2-mgmt.rrze.uni-erlangen.de", "duration": "PT10S", "parallel": 1, "bandwidth": 50000000, "ip-version": 4, "window-size": 1024000}, "type": "throughput"}, "results": [null]}: Traceback (most recent call last):#012  File "/usr/lib/pscheduler/commands/../classes/tool/iperf3/merged-results", line 26, in <module>#012    dest_results   = result_list[1]#012IndexError: list index out of range#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 534, in tasks_uuid_runs_run#012    [ result_full, succeeded, run, task ])#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 112, in dbcursor_query#012    raise ex#012InternalError: Unable to get merged result on {"test": {"spec": {"udp": true, "dest": "pstest2.geant.carnet.hr", "schema": 1, "source": "psps-test2-mgmt.rrze.uni-erlangen.de", "duration": "PT10S", "parallel": 1, "bandwidth": 50000000, "ip-version": 4, "window-size": 1024000}, "type": "throughput"}, "results": [null]}: Traceback (most recent call last):#012  File "/usr/lib/pscheduler/commands/../classes/tool/iperf3/merged-results", line 26, in <module>#012    dest_results   = result_list[1]#012IndexError: list index out of range
Jun 12 13:12:12 pstest2 runner WARNING  134287: Unable to update run https://pstest2.geant.carnet.hr/pscheduler/tasks/a150319e-cd2e-4166-84ea-4ebae0ba01db/runs/b572656f-e025-4bb1-a3dc-a83a64b6afcc: 500 Unable to get merged result on {"test": {"spec": {"udp": true, "dest": "pstest2.geant.carnet.hr", "schema": 1, "source": "psps-test2-mgmt.rrze.uni-erlangen.de", "duration": "PT10S", "parallel": 1, "bandwidth": 50000000, "ip-version": 4, "window-size": 1024000}, "type": "throughput"}, "results": [null]}: Traceback (most recent call last):#012  File "/usr/lib/pscheduler/commands/../classes/tool/iperf3/merged-results", line 26, in <module>#012    dest_results   = result_list[1]#012IndexError: list index out of range
```

**Comment by vvidic** [comment] 2017-06-12 11:23
Might be related to #469 and #474

**Comment by daldoyle** [comment] 2017-07-03 12:56
I think this may be a duplicate of another merged-results issue, but will double check. iperf3 shouldn't ever be getting called with 1 participant, so I'll have to see what is going on here but at the very least make merged-results not bomb out like that.

**Comment by daldoyle** [comment] 2017-07-16 23:59
Not sure why it ultimately happened, but the commit here
https://github.com/perfsonar/pscheduler/commit/81392b4110199a1f373386657628bc6b2e24de88
should at least prevent it from bombing out.

**Closed by daldoyle** 2017-07-16 23:59 UTC
Labels: bug
