### ISSUE TITLE
pscheduler underestimates runtime for some owping tests

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#927] opened 2019-09-20 12:06 UTC
Hi Mark,

Here you will see how pscheduler expects a test will finish in 60s, but it completes in 67s, which I believe is the reason for this issue. Please note this is a reproduction of the test case and is based on my VMs. The reporter is running these on a physical box.

I can't tell if it is specific to my limited resources or not.
```
[ivan@psu-71-72 ~]$ pscheduler task --debug latency -p 1008 -i 0.00005 -c 1000000 --dest psu-71-73
2019-09-20T13:59:35 Debug started
2019-09-20T13:59:35 Assistance is from localhost
2019-09-20T13:59:35 Forcing default slip of PT5M
2019-09-20T13:59:35 Converting to spec via https://localhost/pscheduler/tests/latency/spec
Submitting task...
2019-09-20T13:59:35 Fetching participant list
2019-09-20T13:59:35 Spec is: {"dest": "psu-71-73", "packet-padding": 1008, "packet-interval": 5e-05, "packet-count": 1000000, "schema": 1}
2019-09-20T13:59:35 Params are: {'spec': '{"dest": "psu-71-73", "packet-padding": 1008, "packet-interval": 5e-05, "packet-count": 1000000, "schema": 1}'}
2019-09-20T13:59:36 Got participants: {u'participants': [None], u'null-reason': u'No source specified'}
2019-09-20T13:59:36 Lead is None
2019-09-20T13:59:36 Null reason is No source specified
2019-09-20T13:59:36 Pinging https://localhost/pscheduler/
2019-09-20T13:59:36 localhost is up
2019-09-20T13:59:36 Posting task to https://localhost/pscheduler/tasks
2019-09-20T13:59:36 Data is {'test': {'type': 'latency', 'spec': {u'dest': u'psu-71-73', u'packet-padding': 1008, u'packet-interval': 5e-05, u'packet-count': 1000000, u'schema': 1}}, 'schedule': {'slip': 'PT5M'}}
Task URL:
https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309
2019-09-20T13:59:41 Posted https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309
2019-09-20T13:59:41 Submission diagnostics:
2019-09-20T13:59:41   Hints:
2019-09-20T13:59:41     requester: ::1
2019-09-20T13:59:41     server: ::1
2019-09-20T13:59:41   Identified as everybody, local-interfaces
2019-09-20T13:59:41   Classified as default, friendlies
2019-09-20T13:59:41   Application: Hosts we trust to do everything
2019-09-20T13:59:41     Group 1: Limit 'always' passed
2019-09-20T13:59:41     Group 1: Want all, 1/1 passed, 0/1 failed: PASS
2019-09-20T13:59:41     Application PASSES
2019-09-20T13:59:41   Application: Defaults applied to non-friendly hosts
2019-09-20T13:59:41     Group 1: Limit 'innocuous-tests' passed
2019-09-20T13:59:41     Group 1: Limit 'throughput-default-time' failed: Test is not 'throughput'
2019-09-20T13:59:41     Group 1: Limit 'idleex-default' failed: Test is not 'idleex'
2019-09-20T13:59:41     Group 1: Want any, 1/3 passed, 2/3 failed: PASS
2019-09-20T13:59:41     Application PASSES
2019-09-20T13:59:41   Proposal meets limits
2019-09-20T13:59:41   Priority set to default of 0
Running with tool 'owping'
Fetching first run...
2019-09-20T13:59:41 Fetching https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309/runs/first
2019-09-20T13:59:54 Handing off: pscheduler watch --first --debug https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309
2019-09-20T13:59:54 Debug started
2019-09-20T13:59:54 Fetching https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309
2019-09-20T13:59:54 Fetching next run from https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309/runs/first

Next scheduled run:
https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309/runs/3a788d37-a9df-47a0-97ac-62e8c316fe72
Starts 2019-09-20T13:59:56+02 (~0 seconds)
Ends   2019-09-20T14:00:57+02 (~60 seconds)
Waiting for result...

2019-09-20T14:01:03 Calling ['pscheduler', 'result', '--quiet', '--format', 'text/plain', '--debug', u'https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309/runs/3a788d37-a9df-47a0-97ac-62e8c316fe72']
Run did not complete: Failed

Limit system diagnostics for this run:

  Hints:
    requester: ::1
    server: ::1
  Identified as everybody, local-interfaces
  Classified as default, friendlies
  Application: Hosts we trust to do everything
    Group 1: Limit 'always' passed
    Group 1: Want all, 1/1 passed, 0/1 failed: PASS
    Application PASSES
  Application: Defaults applied to non-friendly hosts
    Group 1: Limit 'innocuous-tests' passed
    Group 1: Limit 'throughput-default-time' failed: Test is not 'throughput'
    Group 1: Limit 'idleex-default' failed: Test is not 'idleex'
    Group 1: Want any, 1/3 passed, 2/3 failed: PASS
    Application PASSES
  Proposal meets limits
  Priority set at 5:
    Initial priority  (Set to 0)
    Friendly requester  (+5)


Error:
    Process took too long to run.

Diagnostics from localhost:
  No diagnostics.

Error from localhost:
  No error.
2019-09-20T14:01:04 Fetching next run from https://localhost/pscheduler/tasks/7044557b-5db7-45c2-8c6f-366d3f37b309/runs/next

No further runs scheduled.
```

```
[ivan@psu-71-72 ~]$ time owping -c 1000000 -s 1008 -i 0.00005 psu-71-73
owping: FILE=time.c, LINE=118, NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
Approximately 52.9 seconds until results available

--- owping statistics from [psU-71-72.rrze]:9698 to [psu-71-73]:9832 ---
SID:    00000049e12f3e186470867a07a37613
first:  2019-09-20T14:01:29.349
last:   2019-09-20T14:02:19.354
1000000 sent, 891 lost (0.089%), 0 duplicates
one-way delay min/median/max = 0.0367/0.2/10.8 ms, (err=0.02 ms)
one-way jitter = 0.2 ms (P95-P50)
hops = 0 (consistently)
no reordering


--- owping statistics from [psu-71-73]:9419 to [psU-71-72.rrze]:9490 ---
SID:    00000048e12f3e1867c0f451e67b5cc3
first:  2019-09-20T14:01:29.348
last:   2019-09-20T14:02:19.362
1000000 sent, 3515 lost (0.351%), 0 duplicates
one-way delay min/median/max = 0.0229/0.2/18.2 ms, (err=0.02 ms)
one-way jitter = 0.3 ms (P95-P50)
hops = 0 (consistently)
no reordering


real    1m6.970s
user    0m20.775s
sys     0m43.921s
```

**Comment by arlake228** [comment] 2019-10-07 14:28
Discussed in on dev call, and we think this is a resource problem. Investigate more if you can and/or update this issue if it persists or encounter in other places.

**Comment by tonin** [comment] 2020-03-09 12:10
Probably a duplicate of #967

**Closed** 2020-03-25 19:46 UTC
