### ISSUE TITLE
High-latency links cause throughput tests to fail

### ISSUE THREAD

**Issue by lbsou** [perfsonar/pscheduler#868] opened 2019-06-26 12:44 UTC
I did a bit of testing with two perfsonar server for the last 3 days and I came across a problem

I tried to use the fonctionnality "Single-ended testing" with iperf and it's not fully working. The task run, iperf3 see the connection, but result in this error : 

iperf3: the client has unexpectedly closed the connection

Any idea why?

Tested with iperf 3.6 and pS-Toolkit-4.1.6-CentOS7-FullInstall-x86_64-2019Feb20.iso on barebone servers.

**Comment by mfeit-internet2** [comment] 2019-06-26 18:59
Single-ended testing is for use when the remote server is running an open iperf2/iperf3/nuttcp server and not pScheduler.  Having a single-ended test to a pScheduler server fail would be the expected behavior.

**Comment by lbsou** [comment] 2019-06-26 19:36
Hi, 

This is exactly what i'm trying to do : test between a perfsonar server and a server with only iperf running and it fail with the client has unexpectedly closed the connection.

**Comment by mfeit-internet2** [comment] 2019-06-26 20:18
I'm going to need more detail than that; this feature is well-tested, in production and works just fine when I set it up here:

```
[pscheduler@dev1]$ pscheduler task throughput --dest dev2 --duration PT10S --single-ended
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/914dfcbd-d2ba-47d4-80fb-78b73ba8ae56
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/914dfcbd-d2ba-47d4-80fb-78b73ba8ae56/runs/d545ae00-4fb9-4384-aba1-ebc789156792
Starts 2019-06-26T15:42:05-04 (~2 seconds)
Ends   2019-06-26T15:42:24-04 (~18 seconds)
Waiting for result...

* Stream ID 5
Interval       Throughput     Retransmits    Current Window 
0.0 - 1.0      2.58 Gbps      585            195.48 KBytes  
1.0 - 2.0      2.83 Gbps      720            183.90 KBytes  
2.0 - 3.0      2.81 Gbps      675            183.90 KBytes  
3.0 - 4.0      2.57 Gbps      585            209.96 KBytes  
4.0 - 5.0      2.06 Gbps      405            253.40 KBytes  
5.0 - 6.0      2.17 Gbps      450            225.89 KBytes  
6.0 - 7.0      2.23 Gbps      495            182.45 KBytes  
7.0 - 8.0      1.93 Gbps      450            222.99 KBytes  
8.0 - 9.0      2.15 Gbps      495            185.34 KBytes  
9.0 - 10.0     2.51 Gbps      585            185.34 KBytes  

Summary
Interval       Throughput     Retransmits    
0.0 - 10.0     2.39 Gbps      5445

No further runs scheduled.
```

Second host:
```
[pscheduler@dev2]$ iperf3 -s 
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 10.0.0.1, port 34290
[  5] local 10.0.0.2 port 5201 connected to 10.0.0.1 port 34292
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   296 MBytes  2.48 Gbits/sec                  
[  5]   1.00-2.00   sec   335 MBytes  2.81 Gbits/sec                  
[  5]   2.00-3.00   sec   338 MBytes  2.83 Gbits/sec                  
[  5]   3.00-4.00   sec   309 MBytes  2.59 Gbits/sec                  
[  5]   4.00-5.00   sec   245 MBytes  2.06 Gbits/sec                  
[  5]   5.00-6.00   sec   258 MBytes  2.17 Gbits/sec                  
[  5]   6.00-7.00   sec   265 MBytes  2.22 Gbits/sec                  
[  5]   7.00-8.00   sec   235 MBytes  1.97 Gbits/sec                  
[  5]   8.00-9.00   sec   251 MBytes  2.11 Gbits/sec                  
[  5]   9.00-10.00  sec   297 MBytes  2.49 Gbits/sec                  
[  5]  10.00-10.04  sec  12.4 MBytes  2.83 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.04  sec  2.78 GBytes  2.38 Gbits/sec                  receiver
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

Is there any chance you're running iperf and not iperf3?

**Comment by lbsou** [comment] 2019-06-27 15:15
Hi and thanks for the reply,

I did some more testing :

If I do a single ended test between two server in the same LAN, there is no problem.

If I do a the same test between two server over a WAN link (satellite) with 560ms of latency, I get error.

### Perfsonar server

```
[root@perfsonar]# iperf3 -v
iperf 3.6 (cJSON 1.5.2)
Linux perfsonar 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication
```


```
[root@perfsonar]# pscheduler task throughput --duration PT5S --source 10.1.1.17 --ip-version 4 --dest 10.1.2.27 --window-size 2097152 --parallel 5 --source-node 10.1.1.17 --dest-node 10.1.2.27 --single-ended --zero-copy

Submitting task...
Task URL:
https://10.1.1.17/pscheduler/tasks/34429555-430e-43a5-8edf-04450b7df9ab
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://10.249.143.17/pscheduler/tasks/34429555-430e-43a5-8edf-04450b7df9ab/runs/3de37ec3-81c4-4360-bcdf-d24a27db5e4e
Starts 2019-06-27T15:11:10Z (~7 seconds)
Ends   2019-06-27T15:11:24Z (~13 seconds)
Waiting for result...

Run did not complete: Failed

Diagnostics from 10.249.143.17:
  No diagnostics.

Error from 10.249.143.17:
  iperf3 returned an error:
  Process took too long to run.

No further runs scheduled.
```

### Client

```
root@iperf:~# iperf3 -v
iperf 3.6 (cJSON 1.5.2)
Linux rr17rrsssvm027 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing
```

```
# iperf3 -s
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 10.1.1.17, port 52554
[  6] local 10.1.2.27 port 5201 connected to 10.1.1.17 port 41632
[ 11] local 10.1.2.27 port 5201 connected to 10.1.1.17 port 57595
[ 15] local 10.1.2.27 port 5201 connected to 10.1.1.17 port 51973
[ 17] local 10.1.2.27 port 5201 connected to 10.1.1.17 port 44489
[ 19] local 10.1.2.27 port 5201 connected to 10.1.1.17 port 55682
[ ID] Interval           Transfer     Bitrate
[  6]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
[ 11]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
[ 15]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
[ 17]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
[ 19]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
[SUM]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[  6]   1.00-2.00   sec  40.1 KBytes   329 Kbits/sec
[ 11]   1.00-2.00   sec  40.1 KBytes   329 Kbits/sec
[ 15]   1.00-2.00   sec  40.1 KBytes   329 Kbits/sec
[ 17]   1.00-2.00   sec  40.1 KBytes   329 Kbits/sec
[ 19]   1.00-2.00   sec  40.1 KBytes   329 Kbits/sec
[SUM]   1.00-2.00   sec   200 KBytes  1.64 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[  6]   2.00-3.00   sec   107 KBytes   875 Kbits/sec
[ 11]   2.00-3.00   sec   102 KBytes   832 Kbits/sec
[ 15]   2.00-3.00   sec   107 KBytes   875 Kbits/sec
[ 17]   2.00-3.00   sec   107 KBytes   875 Kbits/sec
[ 19]   2.00-3.00   sec  90.8 KBytes   744 Kbits/sec
[SUM]   2.00-3.00   sec   513 KBytes  4.20 Mbits/sec
**iperf3: the client has unexpectedly closed the connection**
```

**Comment by mfeit-internet2** [comment] 2019-06-27 17:03
pScheduler allocates a certain amount of time for iperf3 to run.  That includes some additional time in case things go longer than expected.  I don't know the exact amount off the top of my head since I didn't write that plugin, but it's been pretty good for most cases.

If the client side of iperf3 runs long, which I suspect was the case here, the plugin will terminate it  at the scheduled end time so it doesn't overlap with other runs.   I've seen cases where it takes a very long time to connect, either because of slow DNS or something in the middle makes the process go long.

If it works in the lab but not in the field, there's probably something in the field causing it.

**Comment by lbsou** [comment] 2019-07-02 11:51
Hi,

If I do the test manually (iperf3 <-> iperf3) it works.

The problem seems to reside in the 560ms (satellite link).

**Comment by lbsou** [comment] 2019-07-02 12:39
Oh, and can you unclose this post please?

**Comment by lbsou** [comment] 2019-07-02 15:38
Hi Mark, 

As the latency seems to be the problem, I simulated the latency with tc.

`# tc qdisc add dev eth0 root netem delay <delay>ms`
64 bytes from 10.x.x.30: icmp_seq=1 ttl=64 time=<delay + 1> ms
`# pscheduler task throughput --omit PT5S --duration PT25S --source 10.x.x.17 --ip-version 4 --dest 10.x.x.30 --window-size 2097152 --parallel 5 --source-node 10.x.x.17 --dest-node 10.x.x.30  --single-ended --zero-copy`
`# tc qdisc del dev eth0 root netem delay <delay>ms`

The results :

100ms : OK
200ms : OK
250ms : OK
265ms : OK
266ms : OK
267ms : Failed
270ms : Failed
275ms : Failed
300ms : Failed

Hope it helps,

Louis

**Comment by mfeit-internet2** [comment] 2019-07-02 16:11
Yes, thanks for that.  I was about to conduct the same experiment here.

The latency is high enough that the number of back-and-forth exchanges that have to happen for iperf3 to set itself up and get started pushes its execution time to more than scheduled, which results one or both sides being cut off at the knees (depending on single- or double-ended).

Thanks for your persistence with this; it is actually a problem that needs to be addressed.  We've never run any of this over a link with that much latency before, so the behavior does make sense.

The right thing to do here might be to add a `link-latency` parameter to the `throughput` test so the tools can do a rough calculation of how much additional time to add when they estimate how much time they need to run.  I don't want to just add additional time to every test because there are a lot of sites with congested schedules and the extra seconds add up.

I _might_ be able to squeeze this into 4.2 while it's in beta, but it will be resolved for sure in 4.3.

**Comment by lbsou** [comment] 2019-07-02 17:12
Hi Mark, 

Thank you, I will wait for the new option and proceed manually for now.

Have a great day!

Louis

**Comment by mfeit-internet2** [comment] 2019-07-03 20:56
I re-ran your experiment with latencies ranging from 0 to 1,000 ms in 25 ms increments.  Behavior is pretty much linear:

![iperflatency](https://user-images.githubusercontent.com/14113568/60615644-9ebb1d80-9d9d-11e9-9447-41013c7fc33b.png)

The amount of time to add will be easy to calculate.

We will probably also have to restrict the use of this parameter above a certain value to trusted hosts because large values will have the side effect of consuming additional schedule time.

**Comment by lbsou** [comment] 2019-07-04 13:56
Not sure I quite understand... What is the link between the RTT and the runtime?

**Comment by mfeit-internet2** [comment] 2019-07-04 16:29
Iperf3 does a total of [seven back-and-forth exchanges](https://github.com/esnet/iperf/wiki/IperfProtocolSpecification#usual-sequence-of-messages) on its control socket when it runs a measurement.  The longer RTT makes that process take longer, which in turn makes the program run longer.  pScheduler's `iperf3` plugin originally baked in a fixed amount of time for this to take place which, as you observed, isn't enough on a high-latency link.  (The throughput measurement itself doesn't take any longer because it's timed and the program stops doing it after _n_ seconds.)

I've built up new versions of the `throughput` and `iperf3` plugins that support a `link-rtt` parameter that the `iperf3` plugin can use to calculate the right amount of run time.  The default is 200 ms, which gives the same behavior as the previous version and should be more than adequate for most terrestrial paths.  After some final testing tomorrow, this will be in the pipeline for release with 4.2.  I'll see if I can get it incorporated into PWA as well.

**Comment by lbsou** [comment] 2019-07-04 17:25
Ok, I understand.

What would be the modifications needed in PWA as the latency calculation is dynamic?

When the 4.2 version would be release?

**Comment by mfeit-internet2** [comment] 2019-07-04 18:28
Latency is specified as a parameter that should be provided if it is anticipated that a test will use a high-latency link.  pScheduler's _modus operandi_ is that any test must be able to predict how long it will take to run based on its parameters.  The system does not and should not measure the latency when the test is scheduled because conditions could change by the time the test takes place.

**Comment by lbsou** [comment] 2019-07-05 14:53
Is the beta going to be available in ISO format?

**Comment by mfeit-internet2** [comment] 2019-07-08 21:19
I'm happy with the software changes.  Closing.

And yes, the beta will be available as an ISO.

**Closed by mfeit-internet2** 2019-07-08 21:19 UTC
Labels: enhancement

**Comment by lbsou** [comment] 2020-04-22 12:23
Hi Mark!

Any plan on adding this feature to PWA?

Thanks!

**Comment by mfeit-internet2** [comment] 2020-04-22 12:49
Write an issue against psconfig-web for that.  I should probably remember to do that when one of the tests changes.

The very-long-term plan is to have pScheduler's plugins self-enumerate so PWA doesn't have to be modified each time one is added or changed.

**Comment by lbsou** [comment] 2020-04-22 12:52
How can manually modify the command send to the scheduler from the toolkit web-ui? I would need to schedule those tests asap.. thanks Mark!

**Comment by mfeit-internet2** [comment] 2020-04-22 13:12
The only way you'd be able to do it right now would be to modify the test specification in the JSON file that PWA generates.  So where you used to have a throughput test with a spec that looks like...
```
"spec": {
    "dest": "foo.bar.net",
}
```
...you'd have to change it to read...
```
"spec": {
    "schema": 3,
    "dest": "foo.bar.net",
    "link-rtt": "PT0.6S"
}
```

Depending on your situation, it might be less hassle to build a stripped-down mesh with just the throughput tests for the slow links, remove them from your PWA-administered mesh and have your nodes subscribe to both.

**Comment by lbsou** [comment] 2020-04-22 13:58
Not sure if this is possible. One of my server is single ended (standalone iperf).

Do you know if I can modify the toolkit-webui.json file directly, I tried but no luck..

**Comment by lbsou** [comment] 2020-04-22 15:29
To be honest, I was looking to get it work with the toolkit-ui because I'm not quite familiar with the PWA. I did some progress but i'm not really there yet ;)

I managed to get it work, I had wrongly replaced the schema 2 with schema 3, but as I now understand, some specific variable need different schema and both schema needed to be there.

I found out I had an error with  # psconfig validate toolkit-webui.json

This is what it looks like now, and it is now working. Thank you Mark for your help, it is very appreciated.

      "IPERF3_SINGLE_ENDED_0_0" : {
         "spec" : {
            "dest" : "{% address[1] %}",
            "dest-node" : "{% pscheduler_address[1] %}",
            "ip-version" : 4,
            "omit" : "PT2S",
            "schema": 2,
            "single-ended" : true,
            "schema": 3,
            "dest": "{% address[1] %}",
            "link-rtt": "PT0.6S",
            "source" : "{% address[0] %}",
            "source-node" : "{% pscheduler_address[0] %}",
            "zero-copy" : true
         },
         "type" : "throughput"

**Comment by mfeit-internet2** [comment] 2020-04-22 15:31
You have `schema` in there twice.  Remove `"schema": 2` for safety.

And you're welcome.
