### ISSUE TITLE
pscheduler-archiver-esmond doesn't follow HTTP redirect

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#446] opened 2017-05-16 21:54 UTC
If apache in front of esmond is configured to make redirects to reach the esmond archive (ex: from http to https) the pscheduler-archiver-esmond should follow those redirects to post the data.

See https://lists.internet2.edu/sympa/arc/perfsonar-user/2017-05/msg00057.html for more details.

**Comment by mfeit-internet2** [comment] 2017-05-17 11:06
This should be a small tweak to the `url_*` functions in the library.

**Comment by mfeit-internet2** [comment] 2017-05-17 12:26
This doesn't look like a problem with our code:
* The esmond archiver uses the pScheduler library's URL functions.
* Those functions use the `requests` module with the default behavior where redirects are concerned.
* The default behavior for `requests` is to follow redirects, giving up after 30 hops.

Page at a (redacted) site known to be a redirect:
```
% curl http://mailman.example.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://mailman.example.com/mailman/listinfo">here</a>.</p>
</body></html>
```

Same page with our code:
```
python -c 'import pscheduler; print pscheduler.url_get("http://mailman.example.com", json=False)'
(200, u'... Content of redirect destination ...')
```

**Comment by arlake228** [comment] 2017-05-17 14:10
Assigning to self to verify we are doing redirections correctly in archiver.

**Comment by arlake228** [comment] 2017-05-18 16:22
After talking with Dan who saw a similar issue, I think the problem is with fundamentally how redirects are supposed to work in HTTP If you try to POST. According to the HTTP spec you are not supposed to resubmit the POST, you are supposed to perform a GET to the URL returned by the HTTP 30X response. This is exactly what the requests library does, which in our case is telling esmond to query all the data of the archive...yikes.

Probably the fix for this is to make sure a trailing slash is on the end of the URL (so it does not ned a redirect), disable automatic redirect following in the requests library for POSTs, catch the 30X return code, and either print an error message or resubmit the POST to the new URL manually.

**Closed** 2017-05-30 15:06 UTC
