### ISSUE TITLE
Debian databases don't appear to be setup correctly

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#243] opened 2016-12-06 16:14 UTC
Running the latest pscheduler from the snapshot repository, database setup seems to fail. I see a variety of errors, for example:

```
Exception: ProgrammingError: function scheduling_class_background_multi() does not exist#012LINE 28: ...                      AND test.scheduling_class = scheduling...#012                                                              ^#012HINT:  No function matches the given name and argument types. You might need to add explicit type casts.#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/lib/pscheduler/daemons/runner", line 640, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/lib/pscheduler/daemons/runner", line 552, in main_program#012    """, [refresh]);#012ProgrammingError: function scheduling_class_background_multi() does not exist#012LINE 28: ...                      AND test.scheduling_class = scheduling...#012                                                              ^#012HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

They seem to be referencing some somewhat newer changes (as in the past couple weeks) changes to the DB, so hopefully just some updates to the Debian database setup is in order.

**Comment by mfeit-internet2** [comment] 2016-12-07 13:56
There was something that got pushed a few nights ago that shouldn't have been, so it's entirely possible that the build happened on this.  It was fixed within a couple of hours.

I have #110 open on making things fail if there's an error in the SQL that loads the database.

**Comment by vvidic** [comment] 2016-12-08 14:41
Not sure what was the ``pscheduler-server`` version that had this problem, but we are trying to switch to postgresql 9.6 to reduce database issues. Let me know which repo is used so we can test if the issue is solved by upgrading the package.

**Comment by arlake228** [comment] 2016-12-08 14:54
This was from the snapshot repo the day i posted the issue. Let me know
when the new package is available and I can test.



On December 8, 2016 at 9:41:20 AM, Valentin Vidić (notifications@github.com)
wrote:

Not sure what was the pscheduler-server version that had this problem, but
we are trying to switch to postgresql 9.6 to reduce database issues. Let me
know which repo is used so we can test if the issue is solved by upgrading
the package.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/pscheduler/issues/243#issuecomment-265755574>,
or mute the thread

**Comment by vvidic** [comment] 2016-12-08 15:16
If this is a Debian 8/jessie machine you can try already, but the transition to postgresql 9.6 is not automatic. Better purge the postgresql 9.4 packages and than install ``pscheduler-server`` from scratch.

**Comment by tonin** [comment] 2017-01-13 15:55
This needs to be retested on the current packages we have.  User should have postgres 9.6 automatically.

**Comment by vvidic** [comment] 2017-01-19 14:26
It should be good now with postgres 9.6. What was Debian or Ubuntu version on the failing host so I can recheck?

**Comment by vvidic** [comment] 2017-01-23 12:40
Tested the package install on wheezy, jessie, precise and trusty - all look good now.

**Closed by vvidic** 2017-01-23 12:40 UTC
