### ISSUE TITLE
Unable to get participant data errors

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#322] opened 2017-02-23 16:24 UTC
I'm seeing a few daily errors similar to the following in the ```pscheduler.log``` log file:

```
Feb 23 16:37:52 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Unable to get participant data: OSError: [Errno 32] Broken pipe#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pscheduler/program.py", line 99, in run_program#012    stdout, stderr = process.communicate(stdin, timeout=timeout)#012  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 927, in communicate#012    stdout, stderr = self._communicate(input, endtime, timeout)#012  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1713, in _communicate#012    orig_timeout)#012  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1797, in _communicate_with_poll#012    self._input_offset += os.write(fd, chunk)#012OSError: [Errno 32] Broken pipe#012CONTEXT:  PL/pgSQL function run_alter() line 124 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 107, in dbcursor_query#012    raise ex;#012InternalError: Unable to get participant data: OSError: [Errno 32] Broken pipe#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pscheduler/program.py", line 99, in run_program#012    stdout, stderr = process.communicate(stdin, timeout=timeout)#012  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 927, in communicate#012    stdout, stderr = self._communicate(input, endtime, timeout)#012  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1713, in _communicate#012    orig_timeout)#012  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1797, in _communicate_with_poll#012    self._input_offset += os.write(fd, chunk)#012OSError: [Errno 32] Broken pipe#012CONTEXT:  PL/pgSQL function run_alter() line 124 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
```

How should I investigate further?

**Comment by mfeit-internet2** [comment] 2017-02-23 20:46
Basically a dupe of #255.  Will work the issue there.

**Closed by mfeit-internet2** 2017-02-23 20:46 UTC
