### ISSUE TITLE
pscheduler to send url of the run with each unsuccessful measurement

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#316] opened 2017-02-21 16:00 UTC
This one is needed to enable the ability to retrieve detailed information on failing tasks from the pS GUI. The pS GUI tooltips would then be able to redirect directly to the details of the failure.

Additional consideration:
Since after a period of time, these urls will expire a sanity minimum should be considered

**Comment by mfeit-internet2** [comment] 2017-02-21 16:02
Duplicate of #313.

URLs remain valid for the system's retention period, currently seven days.

**Closed by mfeit-internet2** 2017-02-21 16:02 UTC
Labels: enhancement
