### ISSUE TITLE
3rd party mode stopped working

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#218] opened 2016-11-05 18:04 UTC
3rd party mode seems to have stopped working.

e.g.:

pscheduler task --assist antg-staging.es.net --slip PT10M throughput --source llnl-pt1.es.net --dest antg-staging.es.net
Submitting with assistance from antg-staging.es.net...
Task URL:
https://antg-staging.es.net/pscheduler/tasks/9a67f716-daa6-41a3-8873-d46615184427
Fetching first run...
Run on server was never populated.

same error for:
	pscheduler task --slip PT10M throughput --source llnl-pt1.es.net --dest antg-staging.es.net
	pscheduler task --slip PT10M throughput --dest llnl-pt1.es.net --source antg-staging.es.net
        pscheduler task --assist antg-staging.es.net --slip PT20M throughput --source nettest.lbl.gov --dest test-pt1.es.net

Note: llnl-pt1.es.net is a 3.5 host, all others are 4.0.

**Comment by arlake228** [comment] 2016-11-07 16:42
This is a duplicate of #196. Third-party testing works fine and this is nothing specific to that. If you look at the task you originally posted we can see the run eventually made its way to the schedule https://antg-staging.es.net/pscheduler/tasks/9a67f716-daa6-41a3-8873-d46615184427/runs. The problem is it sometimes takes runs a really long time to get to the schedule.

**Closed by arlake228** 2016-11-07 16:42 UTC
