### ISSUE TITLE
api_has_services errors when given raw IPv6 address 

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#498] opened 2017-07-03 13:27 UTC
If I run the following test, which should work I get an error. Looks like a problem with IPv6 and the api_has_services call. Looks like a new issue because the same test works with something running production. In addition to rtt, can run trace or throughput (both tests that do backward incompatibility checks) and get the exact same error:

```
[rootal@antg-staging ~]# pscheduler task rtt --dest 2606:a000:111c:406c:250:56ff:feb2:244a
Submitting task...
Unable to determine the lead participant: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/test/rtt/participants", line 45, in <module>
    has = pscheduler.api_has_services([source, destination], timeout=3)
  File "/usr/lib/python2.7/site-packages/pscheduler/api.py", line 329, in api_has_services
    for host, service, state in pool.imap(check_one, args, chunksize=1):
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
    raise value
ValueError: invalid literal for int() with base 10: 'a000'
```

**Comment by mfeit-internet2** [comment] 2017-07-13 17:01
Duplicate of #496.  Closing.

**Closed by mfeit-internet2** 2017-07-13 17:01 UTC
